proj_dist: 5.0

morph_filter_ks_size: 3
median_filter_ks_size: 3
morph_filter_iter: 1

prob_max: 0.97
prob_min: 0.12

grid_filter: true

use_disparity: false
use_scan: true

map_frame: "odom"
map_size: 15
map_res: 0.05
origin_update_th: 2.0


detectors_ns: /detectors

detectors:

  -
    name: sample_grass
    # some more values...
    
  - 
    name: lbp


